### ISSUE TITLE
Make dist that just works with require.js

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#45] opened 2015-02-05 01:59 UTC
Currently the way to use omniscient with require.js requires boilerlpate:

```js
require(["react"], React => {
  window.React = React;
  require(["omniscient"], component => {
     // your code here
  });
});
```

This is unfortunate, I believe that could be avoided either by updating UMD wrapper generated or by generating different dists one for AMD one for the current case.

**Comment by cmwelsh** [comment] 2015-02-06 15:50
I had to do a similar thing for making Immutable available within Immstruct with RequireJS. Added this file as a dependency for `immstruct`:

```
// convert Immutable to a window module
define([
    'immutable'
], function (
    Immutable
) {
    window.Immutable = Immutable;
    return Immutable;
});
```

**Comment by mikaelbr** [comment] 2015-02-08 12:35
I think doing something like @cmwelsh suggest is the best alternative here.

**Comment by mikaelbr** [comment] 2015-02-10 07:32
Closing this as I think @cmwelsh has the most feasible solution.

**Closed by mikaelbr** 2015-02-10 07:32 UTC

**Comment by cmwelsh** [comment] 2015-02-10 20:00
RequireJS really needs a "reverse shim" config. `immutable-js` provides AMD support and no global variable if it detects RequireJS, but `immstruct` expects a global variable. Seems like it would be useful for RequireJS to allow attaching a module to an arbitrary key on `window`.

**Comment by cmwelsh** [comment] 2015-03-09 20:22
I ended up including React and Immstruct as script tags before I load RequireJS. My suggestion above worked for development, but in production, with the minified build, the only way to get them to play nice with omniscient and immstruct was to avoid RequireJS.

It would probably save people some trouble if omniscient had the same UMD cruft around their dist files as React. For my own project, we are just going to move to CommonJS like the rest of the ecosystem is doing and not bother with these issues.

**Comment by mikaelbr** [comment] 2015-03-09 20:28
Hi. Thanks for the update. What caused the minifide code not to work? Was it `r.js` not handling nested defines with setting `window.Immutable`? Or that `window` was minified in some way?

Omniscient has UMD, but the issue is injecting the dependencies which AFAIK, browserify can't handle too good. Might be worth doing more research for fixing this, but AMD isn't our first priority.

**Comment by cmwelsh** [comment] 2015-03-10 17:46
It seems like you need to use the RequireJS config option `wrapShim` (added in 2.1.11) to properly resolve things in the minified build. I couldn't get it to work so I gave up.

http://requirejs.org/docs/download.html#2-1-11
